from langchain_groq import ChatGroq
from docx import Document
from docx.shared import Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
from datetime import datetime
import os
from dotenv import load_dotenv

load_dotenv()

def report_writer_agent(state: dict) -> dict:
    """
    Agent 3: Uses Groq LLM to write a natural language report,
    then saves it as a formatted .docx file.
    """
    print("✍️  Report Writer Agent running...")

    anomalies = state["anomalies"]
    insights = state["insights"]
    client_name = state.get("client_name", "Client")

    # --- Build prompt for Groq ---
    anomaly_text = ""
    if anomalies:
        for a in anomalies:
            anomaly_text += f"- {a['source']} | {a['metric']}: {a['change_pct']}% change ({a['severity']} severity)\n"
    else:
        anomaly_text = "No significant anomalies detected this period.\n"

    insight_text = ""
    for i in insights:
        if i["source"] == "GSC":
            insight_text += (
                f"- GSC: {i['total_clicks']} clicks, "
                f"{i['total_impressions']} impressions, "
                f"avg position {i['avg_position']}, "
                f"avg CTR {i['avg_ctr']}%\n"
            )
            insight_text += "  Top queries: " + ", ".join(
                [q["query"] for q in i.get("top_queries", [])]
            ) + "\n"
        elif i["source"] == "Google Ads":
            d = i["data"]
            insight_text += (
                f"- Google Ads: {d.get('impressions')} impressions, "
                f"{d.get('clicks')} clicks, "
                f"CTR {d.get('ctr')}%, "
                f"ROAS {d.get('roas')}x\n"
            )
        elif i["source"] == "GA4":
            insight_text += (
                f"- GA4 {i['metric']}: improved by {i['change_pct']}%\n"
            )

    prompt = f"""
You are an expert digital marketing analyst writing a weekly SEO and performance report for a client.

Client: {client_name}
Report Period: Last 28 days
Date: {datetime.today().strftime('%B %d, %Y')}

ANOMALIES DETECTED:
{anomaly_text}

PERFORMANCE INSIGHTS:
{insight_text}

Write a professional client report with these sections:
1. Executive Summary (2-3 sentences, plain English, highlight the most important finding)
2. Traffic & Engagement (GA4 analysis, what changed and why it might have happened)
3. Search Performance (GSC insights, top queries, visibility trends)
4. Paid Advertising (Google Ads summary, note if demo data)
5. Recommendations (3 clear, actionable bullet points)
6. Next Steps (what will be monitored next week)

Tone: Professional but friendly. Avoid jargon. Write as if explaining to a business owner, not a technical person.
Keep the total report under 500 words.
"""

    llm = ChatGroq(
        model="openai/gpt-oss-20b",
        api_key=os.getenv("GROQ_API_KEY"),
        temperature=0.4,
    )

    print("  → Generating report with Groq LLM...")
    response = llm.invoke(prompt)
    report_text = response.content

    # --- Build .docx ---
    print("  → Building .docx file...")
    doc = Document()

    # Title
    title = doc.add_heading(f"SEO Performance Report — {client_name}", 0)
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER

    # Date
    date_para = doc.add_paragraph(f"Report Date: {datetime.today().strftime('%B %d, %Y')}")
    date_para.alignment = WD_ALIGN_PARAGRAPH.CENTER

    doc.add_paragraph("")  # spacer

    # Report body
    for line in report_text.split("\n"):
        if line.strip() == "":
            doc.add_paragraph("")
        elif line.startswith("#"):
            doc.add_heading(line.replace("#", "").strip(), level=2)
        else:
            doc.add_paragraph(line.strip())

    # Footer note
    doc.add_paragraph("")
    footer = doc.add_paragraph("Generated by SEO Reporting Agent | Powered by Groq LLaMA 3.3")
    footer.alignment = WD_ALIGN_PARAGRAPH.CENTER

    # Save
    os.makedirs("output", exist_ok=True)
    filename = f"output/SEO_Report_{client_name.replace(' ', '_')}_{datetime.today().strftime('%Y%m%d')}.docx"
    doc.save(filename)

    print(f"✅ Report saved → {filename}")

    return {
        **state,
        "report_text": report_text,
        "report_file": filename,
    }